### ISSUE TITLE
No results when searching project name

### ISSUE THREAD

**Issue by doup** [Pagefind/pagefind#795]
We're adding Pagefind ([see PR](https://github.com/bevyengine/bevy-website/pull/1935)) to the [Bevy website](https://bevyengine.org), but I've found a surprising behavior, when searching for `bevy` I get zero results. Even if the term is mentioned in a lot of pages. The word is both the project name and an English word, so… I don't get it. 😅 

Thanks!

<img width="865" alt="Image" src="https://github.com/user-attachments/assets/f7e4bae0-6786-40a2-9d90-c413e662254f" />

---

Versions: `1.2.0`, `1.3.0` and `1.4.0-alpha.1`

```yaml
site: public
output_path: static/pagefind
exclude_selectors:
  - ".tree-menu"
  - ".example__back"
  - ".example__github"
```
